export default {
    login: 'tbuzzalino',
    id: 54788347,
    node_id: 'MDQ6VXNlcjU0Nzg4MzQ3',
    avatar_url: 'https://avatars.githubusercontent.com/u/54788347?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/tbuzzalino',
    html_url: 'https://github.com/tbuzzalino',
    followers_url: 'https://api.github.com/users/tbuzzalino/followers',
    following_url:
        'https://api.github.com/users/tbuzzalino/following{/other_user}',
    gists_url: 'https://api.github.com/users/tbuzzalino/gists{/gist_id}',
    starred_url:
        'https://api.github.com/users/tbuzzalino/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/tbuzzalino/subscriptions',
    organizations_url: 'https://api.github.com/users/tbuzzalino/orgs',
    repos_url: 'https://api.github.com/users/tbuzzalino/repos',
    events_url: 'https://api.github.com/users/tbuzzalino/events{/privacy}',
    received_events_url:
        'https://api.github.com/users/tbuzzalino/received_events',
    type: 'User',
    site_admin: false,
    name: 'Tomas Buzzalino',
    company: null,
    blog: '',
    location: 'Argentina',
    email: null,
    hireable: null,
    bio: 'Full Stack Developer',
    twitter_username: 'tomibuzzalino',
    public_repos: 11,
    public_gists: 0,
    followers: 5,
    following: 4,
    created_at: '2019-09-02T03:43:24Z',
    updated_at: '2021-08-19T23:26:32Z',
};
